name: travel
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.3
  geolocator: ^10.1.0
  json_annotation: ^4.8.1
  json_serializable: ^6.0.0
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.4
  build_runner: ^2.4.6
  lottie: ^2.0.0
  http: ^1.1.0
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/